apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen       80;
            server_name  localhost;

            root   /var/www/html;
            index  index.php index.html;

            location / {
                try_files $uri $uri/ /index.php;
            }

            location ~ \.php$ {
                fastcgi_pass   php:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
                include        fastcgi_params;
            }

            location /front/ {
                alias /var/www/html/front/;
            }

            error_page 404 /404.html;

            error_log  /dev/stdout;
            access_log /dev/stdout;
        }
    }
