apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-custom
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-custom
    spec:
      containers:
        - name: web-custom
          image: hrchlhck/web-custom
          ports:
            - containerPort: 80
              name: http