apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["tail", "-f", "/dev/null"]
      envFrom:
        - configMapRef: 
            name: meu-configmap