apiVersion: v1
kind: PersistentVolume
metadata:
  name: pod-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: "" 
  local:
    path: /tmp/teste
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - secplab00
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-pvc
spec:
  selector:
    matchLabels:
      app: ubuntu
  resources:
    requests:  
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: pod-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
    - image: ubuntu:22.04
      name: ubuntu
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - mountPath: /mnt
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pod-pvc
