apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web-stateful
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: web-stateful
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-stateful
spec:
  replicas: 3
  serviceName: web
  selector:
    matchLabels:
      app: web-stateful
  template:
    metadata:
      labels:
        app: web-stateful
    spec:
      containers:
        - name: web-stateful
          image: hrchlhck/web-custom
          ports:
            - containerPort: 80
              name: http